### ISSUE TITLE
PM Permit cannot be turned off!

### ISSUE THREAD

**Issue by Mevq1hgs** [TeamDaisyX/DaisyXMusic#114]
The command /pmpermit does not seems to be working. Even when the PMPERMIT variable is set to DISABLE, pmpermit is still present.

**Comment by Hunter-XDD** [comment]
Okay send logs for this issue i will try to fix it asap

**Comment by Mevq1hgs** [comment]
No logs....
The command /pmpermit is not recognized by the bot. So no log comes up, when the command is used.

**Comment by Mevq1hgs** [comment]
Any update?
