### ISSUE TITLE
Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by The-Quaint** [TeamDaisyX/DaisyXMusic#119]
I don't know why i get this error every time. How can i fix it?
The logs i am getting 👇

[youtube] fm-nXA-K0Dg: Downloading webpage
[youtube] fm-nXA-K0Dg: Downloading thumbnail ...
[youtube] fm-nXA-K0Dg: Writing thumbnail to: Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.webp
[download] Destination: Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.webm

[download]   0.0% of 3.13MiB at 168.96KiB/s ETA 00:19
[download]   0.1% of 3.13MiB at 490.49KiB/s ETA 00:06
[download]   0.2% of 3.13MiB at  1.10MiB/s ETA 00:02
[download]   0.5% of 3.13MiB at  2.30MiB/s ETA 00:01
[download]   1.0% of 3.13MiB at  1.08MiB/s ETA 00:02
[download]   2.0% of 3.13MiB at  1.26MiB/s ETA 00:02
[download]   4.0% of 3.13MiB at  1.72MiB/s ETA 00:01
[download]   8.0% of 3.13MiB at  2.60MiB/s ETA 00:01
[download]  15.9% of 3.13MiB at  4.18MiB/s ETA 00:00
[download]  31.9% of 3.13MiB at  6.97MiB/s ETA 00:00
[download]  63.9% of 3.13MiB at 11.91MiB/s ETA 00:00
[download] 100.0% of 3.13MiB at  9.11MiB/s ETA 00:00
[download] 100% of 3.13MiB in 00:00
[ffmpeg] Destination: Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.mp3
Deleting original file Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.webm (pass -k to keep)
Failed to decode "Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.webm". The value does not represent an existing local file, HTTP URL, or valid file id.
[Errno 2] No such file or directory: 'Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.webm'

**Comment by Hunter-XDD** [comment]
Okay i will check it again
