### ISSUE TITLE
How edit the SUDO_USERS ?

### ISSUE THREAD

**Issue by Soheib1378** [TeamDaisyX/DaisyXMusic#17]
As i don't want deploy to heroku, how put my id in this line :

<div class="application-main " data-commit-hovercards-enabled="" data-discussion-hovercards-enabled="" data-issue-and-pr-hovercards-enabled="" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><div itemscope="" itemtype="http://schema.org/SoftwareSourceCode" class="" style="box-sizing: border-box;"><main id="js-repo-pjax-container" data-pjax-container="" style="box-sizing: border-box; display: block;"><div class="container-xl clearfix new-discussion-timeline px-3 px-md-4 px-lg-5" style="box-sizing: border-box; margin-right: auto; margin-left: auto; max-width: 1280px; padding-left: 16px !important; padding-right: 16px !important;"><div id="repo-content-pjax-container" class="repository-content " style="box-sizing: border-box;"><div style="box-sizing: border-box;"><div data-target="readme-toc.content" class="Box mt-3 position-relative
    " style="box-sizing: border-box; background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px; position: relative !important; margin-top: 16px !important;"><div itemprop="text" class="Box-body p-0 blob-wrapper data type-python  gist-border-0" style="box-sizing: border-box; padding: 0px !important; border-bottom: 1px solid var(--color-border-primary); overflow: auto hidden; margin-bottom: -1px; border-bottom-right-radius: 6px; border-bottom-left-radius: 6px;">SUDO_USERS = list(map(int, getenv("SUDO_USERS").split()))</div></div><details class="details-reset details-overlay details-overlay-dark" id="jumpto-line-details-dialog" style="box-sizing: border-box; display: block;"><summary data-hotkey="l" aria-label="Jump to line" role="button" style="box-sizing: border-box; display: list-item; cursor: pointer; list-style: none;"></summary></details></div></div></div></main></div></div><div class="footer container-xl width-full p-responsive" role="contentinfo" style="box-sizing: border-box; margin-right: auto; margin-left: auto; max-width: 1280px; width: 360px; padding-right: 16px !important; padding-left: 16px !important; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><div class="position-relative d-flex flex-row-reverse flex-lg-row flex-wrap flex-lg-nowrap flex-justify-center flex-lg-justify-between pt-6 pb-2 mt-6 f6 color-text-secondary border-top color-border-secondary " style="box-sizing: border-box; border-top-width:  !important; border-top-style:  !important; border-color: var(--color-border-secondary) !important; color: var(--color-text-secondary) !important; flex-flow: row-reverse wrap !important; justify-content: center !important; position: relative !important; margin-top: 40px !important; padding-bottom: 8px !important; padding-top: 40px !important; font-size: 12px !important; display: flex !important;"><ul class="list-style-none d-flex flex-wrap col-12 col-lg-5 flex-justify-center flex-lg-justify-between mb-2 mb-lg-0" style="box-sizing: border-box; padding-left: 0px; margin-top: 0px; margin-bottom: 8px !important; width: 328px; flex-wrap: wrap !important; justify-content: center !important; list-style: none !important; display: flex !important;"><br class="Apple-interchange-newline"></ul></div></div>

**Comment by InukaAsith** [comment]
fill SUDO_USERS in example.env and renme it to local.env

**Comment by InukaAsith** [comment]
Everything in config you only need to fill and rename example.env to local.env. Good Luck
