### ISSUE TITLE
/play <reply in audio file> not working !... Fix it 

### ISSUE THREAD

**Issue by OxyNotOp** [TeamDaisyX/DaisyXMusic#18]

**Comment by OxyNotOp** [comment]
/play <reply in audio file> not working

**Comment by InukaAsith** [comment]
Thanks for informing. We will fix it today

**Comment by InukaAsith** [comment]
Fixed

**Comment by OxyNotOp** [comment]
Ohh wait lemme check

**Comment by OxyNotOp** [comment]
Maybe it's not working bro !... Check again

**Comment by InukaAsith** [comment]
Should work now

**Comment by OxyNotOp** [comment]
I'll give you one advice make new module of (/play reply in audio) and
upload maybe it's work !..

**Comment by OxyNotOp** [comment]
Okay I'll check

**Comment by InukaAsith** [comment]
fixed
