### ISSUE TITLE
ARQ-API__ERROR 

### ISSUE THREAD

**Issue by Aswin-Raj-TG** [TeamDaisyX/DaisyXMusic#25]
#bug

Error Always In ARQ

I havnt edited 
- ARQ_API
- SAAVN
- DEEZER

please solve this issue fast

**Comment by InukaAsith** [comment]
Try now bro

**Comment by InukaAsith** [comment]
fixed

**Comment by Aswin-Raj-TG** [comment]
> fixed

Thanks
