### ISSUE TITLE
Fix The Bugs 

### ISSUE THREAD

**Issue by Aswin-Raj-TG** [TeamDaisyX/DaisyXMusic#33]
🐞 1. In play.py | callback("menu")
         : The leave (⏹)button isnt working

🐞  2. Gcast.py 
         : Gcast.py  is not working only just showing "starting gcast"

🐞  3. admins.py | chatmember_updated.py
        : the admins is not at all updating when use 
          /adminreset & /admincache

**Comment by InukaAsith** [comment]
Busy with studies these days.

**Comment by Aswin-Raj-TG** [comment]
> Busy with studies these days.
> I will fix soon

Oh Noooo. 😢

**Comment by Aswin-Raj-TG** [comment]
.
