### ISSUE TITLE
Read Before Opening YTDL Issue

### ISSUE THREAD

**Issue by InukaAsith** [TeamDaisyX/DaisyXMusic#92]
Youtube is made for humans. not robots

and also youtube officially not allowing to download things from youtube
this is the reason behind this issue
I dont know what to do. I did the only thing i can do by adding saavn and deezer play.

If anyone have a solution. We are always open

> HTTP Error 429: Too Many Requests or 402: Payment Required
> 
> These two error codes indicate that the service is blocking your IP address because of overuse. Usually this is a soft block meaning that you can gain access again after solving CAPTCHA. Just open a browser and solve a CAPTCHA the service suggests you and after that pass cookies to youtube-dl. Note that if your machine has multiple external IPs then you should also pass exactly the same IP you've used for solving CAPTCHA with --source-address. Also you may need to pass a User-Agent HTTP header of your browser with --user-agent.
> 
> If this is not the case (no CAPTCHA suggested to solve by the service) then you can contact the service and ask them to unblock your IP address, or - if you have acquired a whitelisted IP address already - use the --proxy or --source-address options to select another IP address.

https://github.com/ytdl-org/youtube-dl/issues/23638

**Comment by Nagarajking** [comment]
Bot not support in my group

**Comment by Nagarajking** [comment]
> Bot not support in my group 

Hello 🙄

**Comment by scprojectslk** [comment]
yt-dlp 🙄
